name: Deploy on Production
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and Deploy on Production
        run: echo "hello"

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          notify_when: 'failure'
          mention_users: 'U0160UUNH8S,U0080UUAA9N'
          mention_users_when: 'failure,warnings'
          mention_groups: 'SAZ94GDB8'
          mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
