name: Deploy on Production
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and Deploy on Production
        run: echo "hello"


      - uses: ravsamhq/notify-slack-action@v2
          if: always()
          with:
            status: ${{ job.status }} # required
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }} # required
