name: Deploy on Production
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and Deploy on Production
        run: echo "hell0o" 

      - name: get Inputs
        run: echo "${{ job.status }}"

      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          # mention_users: "U0160UUNH8S,U0080UUAA9N"
          # mention_users_when: "failure,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
